global:
  image:
    repository: rajsingh8826
    tag: 
    pullPolicy: IfNotPresent
  containerPort: 8080
  servicePort: 8080
ui:
  serviceType: LoadBalancer
  env:
    - name: JAVA_OPTS
      value: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
    - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
      value: "true"
    - name: RETAIL_UI_ENDPOINTS_CATALOG
      value: "http://catalog:8080"
    - name: RETAIL_UI_ENDPOINTS_CARTS
      value: "http://carts:8080"
    - name: RETAIL_UI_ENDPOINTS_ORDERS
      value: "http://orders:8080"
    - name: RETAIL_UI_ENDPOINTS_CHECKOUT
      value: "http://checkout:8080"
    - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
      value: "true"
    - name: LOGGING_LEVEL_ROOT
      value: "INFO"
    - name: RETAIL_UI_CHAT_ENABLED
      value: "true"
    - name: RETAIL_UI_CHAT_PROVIDER
      value: "mock"
    - name: RETAIL_UI_CHAT_TEMPERATURE
      value: "0.6"
    - name: RETAIL_UI_CHAT_MAX_TOKENS
      value: "300"
    - name: RETAIL_UI_CHAT_OPENAI_BASE_URL
      value: "http://localhost:8080"

    - name: RETAIL_UI_CHAT_PROMPT
      value: "You are a helpful assistant for an online retail store. You can answer questions about products, assist with orders, and provide information about the store's services. Always be polite and provide accurate information based on the user's queries."
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_SDK_DISABLED
      value: "false" # <--- This is the "Master Override"
    - name: OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED
      value: "true"  # <--- This forces the auto-config to run
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger.monitoring.svc.cluster.local:4318"




orders:
  hasDatabase: true
  dbImage: postgres:16.1
  dbPort: 5432
  dbEnv: 
    - name: POSTGRES_USER
      value: "orders_user"
    - name: POSTGRES_PASSWORD
      value: "12345"
    - name: POSTGRES_DB
      value: "orders"
  exporter:
    enabled: true
    image: prometheuscommunity/postgres-exporter:v0.15.0
    port: 9187
    # The connection string: postgres://user:password@host:port/dbname?sslmode=disable
    dsn: "postgresql://orders_user:12345@localhost:5432/orders?sslmode=disable"
  env:
    - name: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
      value: "orders-db:5432"
    - name: RETAIL_ORDERS_PERSISTENCE_PASSWORD
      value: "12345"
    - name: RETAIL_ORDERS_PERSISTENCE_PROVIDER
      value: "postgres"
    - name: RETAIL_ORDERS_PERSISTENCE_NAME
      value: "orders"
    - name: RETAIL_ORDERS_PERSISTENCE_USERNAME
      value: "orders_user"
    - name: RETAIL_ORDERS_MESSAGING_PROVIDER
      value: "rabbitmq"
    - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES
      value: "rabbitmq:5672"
    - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
      value: "rabbitmq"
    - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
      value: "12345"
    - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
      value: "true"
    - name: LOGGING_LEVEL_ROOT
      value: "INFO"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_SDK_DISABLED
      value: "false" # <--- This is the "Master Override"
    - name: OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED
      value: "true"  # <--- This forces the auto-config to run
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger.monitoring.svc.cluster.local:4318"


carts:
  hasDatabase: true
  dbImage: amazon/dynamodb-local:1.20.0
  dbPort: 8000
  env:
    - name: SERVER_TOMCAT_ACCESSLOG_ENABLED
      value: "true"
    - name: RETAIL_CART_PERSISTENCE_PROVIDER
      value: "dynamodb"
    - name: RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT
      value: "http://carts-db:8000"
    - name: RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE
      value: "true"
    - name: AWS_ACCESS_KEY_ID
      value: "key"
    - name: AWS_SECRET_ACCESS_KEY
      value: "dummy"
    - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
      value: "true"
    - name: LOGGING_LEVEL_ROOT
      value: "INFO"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_SDK_DISABLED
      value: "false" # <--- This is the "Master Override"
    - name: OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED
      value: "true"  # <--- This forces the auto-config to run
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger.monitoring.svc.cluster.local:4318"


checkout:
  hasDatabase: true
  dbImage: redis:6-alpine
  dbPort: 6379
  exporter:
    enabled: true
    image: oliver006/redis_exporter:v1.55.0
    port: 9121
    dns: "redis://localhost:6379"
  env:
    - name: RETAIL_CHECKOUT_PERSISTENCE_PROVIDER
      value: "redis"
    - name: RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL
      value: "redis://checkout-db:6379"
    - name: RETAIL_CHECKOUT_ENDPOINTS_ORDERS
      value: "http://orders:8080"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger.monitoring.svc.cluster.local:4318"
    - name: OTEL_SERVICE_NAME
      value: "checkout"

catalog:
  hasDatabase: true
  dbImage: mariadb:10.9
  dbPort: 3306
  dbEnv:
    - name: MYSQL_ROOT_PASSWORD
      value: "12345" 
    - name: MYSQL_USER
      value: "catalog_user"
    - name: MYSQL_PASSWORD
      value: "12345"
    - name: MYSQL_DATABASE
      value: "catalogdb"
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "true" 
  env:
    - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
      value: "catalog-db:3306"
    - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
      value: "12345"
    - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
      value: "mysql"
    - name: RETAIL_CATALOG_PERSISTENCE_NAME
      value: "catalogdb"
    - name: RETAIL_CATALOG_PERSISTENCE_USERNAME
      value: "catalog_user"
    - name: OPENTELEMETRY_TRACES_EXPORTER
      value: "otlp"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger.monitoring.svc.cluster.local:4318"
    - name: OTEL_SERVICE_NAME
      value: "catalog"
    # Go often needs the protocol specified explicitly for OTLP
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
  exporter:
    enabled: true
    image: prom/mysqld-exporter:v0.15.0
    port: 9104
    dsn: "catalog_user:12345@(localhost:3306)/catalogdb"

rabbitmq:
  image: rabbitmq:3-management
  serviceType: LoadBalancer
  extraPorts:
    - name: amqp
      port: 5672
    - name: http
      port: 15672
    - name: prometheus 
      port: 15692
  env:
    - name: RABBITMQ_DEFAULT_USER
      value: "rabbitmq"
    - name: RABBITMQ_DEFAULT_PASS
      value: "12345"
