namespace: retail-store-prod

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/ui
- ../../base/catalog
- ../../base/catalog-db
- ../../base/carts
- ../../base/carts-db
- ../../base/checkout
- ../../base/checkout-db
- ../../base/orders
- ../../base/orders-db
- ../../base/rabbitmq

  

  
  
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: ui
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: catalog
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: carts
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: checkout
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: orders
  
  
  
  
  
  
images:
- name: rabbitmq:3-management-alpine
  newTag: 3-management-alpine
- name: rajsingh8826/retail-carts
  newTag: latest
- name: rajsingh8826/retail-catalog
  newTag: latest
- name: rajsingh8826/retail-checkout
  newTag: latest
- name: rajsingh8826/retail-orders
  newTag: latest
- name: rajsingh8826/retail-ui
  newName: rajsingh8826/retail-ui
  newTag: b21d79e3f91bf5a300660f96c6ce1211ec1e7791
