name: 🚀 Catalog CI

on:
  push:
    paths:
      - 'src/catalog/**'
    branches: ["main"]
    workflow_dispatch:
    
jobs:
  call-security-pipeline:
    uses: ./.github/workflows/security-pipeline.yml
    with:
      image_name: "retail-catalog"
      context: "./src/catalog/"
    secrets: inherit