name: 🚀 Catalog CI

on:
  push:
    paths:
      - './src/catalog/**'
    branches:
      - main
    
jobs:
  call-security-pipeline:
    uses: ./.github/workflows/reusable-build.yml
    with:
      image_name: "retail-catalog"
      context: "./src/catalog/"
    secrets: inherit