name: 🚀 UI CI

on:
  push:
    paths:
      - './src/ui/**'
    branches:
      - main

jobs:
  call-security-pipeline:
    uses: ./.github/workflows/reusable-build.yml@main
    with:
      image_name: "retail-ui"
      context: "./src/ui/"
    secrets: inherit 